### ISSUE TITLE
To be tested

### ISSUE THREAD

**Issue by acazorso7** [BonaDrone/Hackflight#113]
## Feature / Bug description

Just validate de following developments or issues:

- [ ]  **Check**: When we connect to the drone via Android APP with WiFi and push disconnect while flying the drone hover for 30 seconds and then LAND.

- [ ]  **Check**: What happens if we have the drone connected to the APP, not armed and not flying and we disconnect the drone from the APP it must do nothing.

- [ ]  **Check**: Low battery is properly detected and a LAND action is triggered and performed. (issue : #60 #74 #63 , PR: #118)

- [ ]  **Check**: In depth checking of the planner. I have tested with simple hardcoded missions and it works, but we should test a wide range of scenarios. Specifically, what should be tested is that the setpoints that each action/instruction sets to the corresponding controller results in the expected behavior.

- [ ]  **Check**: When executing a mission, if the `aux 1` is switched, control of the drone is taken by the remote control or APP. (issue: #115 , PR: #116)

- [ ]  **Check**: The newly added safety measures when arming the drone. (issue: #61)

- [ ] **Check**: Maximum height limitation (3m) when executing a flight mission. (issue: #85 , PR: #120 )
